export const GET_USER_REQUEST: 'SEND_USER_REQUEST' = 'SEND_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const SET_USER: 'SET_USER' = 'SET_USER';
export const CLEAR_USER: 'CLEAR_USER' = 'CLEAR_USER';

export const ADD_TO_CART: "ADD_TO_CART" = "ADD_TO_CART";
export const REMOVE_FROM_CART: "REMOVE_FROM_CART" = "REMOVE_FROM_CART";
export const CHANGE_ITEM_POSITION: "CHANGE_ITEM_POSITION" = "CHANGE_ITEM_POSITION";
export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART';

export const SEND_EMAIL_REQUEST: 'SEND_EMAIL_REQUEST' = 'SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS: 'SEND_EMAIL_SUCCESS' = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAILED: 'SEND_EMAIL_FAILED' = 'SEND_EMAIL_FAILED'
export const CLEAR_FORGOTPASSWORD_STORE: 'CLEAR_FORGOTPASSWORD_STORE' = 'CLEAR_FORGOTPASSWORD_STORE';

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
export const SHOW_INGREDIENT_DATA: "SHOW_INGREDIENT" = "SHOW_INGREDIENT";

export const SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST' = 'SEND_LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const SEND_LOGOUT_REQUEST: 'SEND_LOGOUT_REQUEST' = 'SEND_LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const SEND_ORDER_REQUEST = "SEND_ORDER_REQUEST";
export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED = "SEND_ORDER_FAILED";

export const SEND_REFRESH_TOKEN_REQUEST: 'SEND_REFRESH_TOKEN_REQUEST' = 'SEND_REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED'; 

export const SEND_REGISTRATION_REQUEST = 'SEND_REGISTRATION_REQUEST'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'

export const SEND_RESET_PASSWORD_REQUEST = 'SEND_RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'SEND_RESET_PASSWORD_FAILED'