export const FEED_WS_CONNECTION_START: 'FEED_WS_CONNECTION_START' = 'FEED_WS_CONNECTION_START';
export const FEED_WS_CONNECTION_SUCCESS: 'FEED_WS_CONNECTION_SUCCESS' = 'FEED_WS_CONNECTION_SUCCESS'; 
export const FEED_WS_CONNECTION_ERROR: 'FEED_WS_CONNECTION_ERROR' = 'FEED_WS_CONNECTION_ERROR';
export const FEED_WS_CONNECTION_CLOSED: 'FEED_WS_CONNECTION_CLOSED' = 'FEED_WS_CONNECTION_CLOSED';
export const FEED_WS_GET_MESSAGE: 'FEED_WS_GET_MESSAGE' = 'FEED_WS_GET_MESSAGE';
export const FEED_WS_SEND_MESSAGE: 'FEED_WS_SEND_MESSAGE' = 'FEED_WS_SEND_MESSAGE';
export const FEED_WS_CONNECTION_CLOSE: 'FEED_WS_CONNECTION_CLOSE' = 'FEED_WS_CONNECTION_CLOSE';

export const PROFILE_WS_CONNECTION_START: 'PROFILE_WS_CONNECTION_START' = 'PROFILE_WS_CONNECTION_START';
export const PROFILE_WS_CONNECTION_SUCCESS: 'PROFILE_WS_CONNECTION_SUCCESS' = 'PROFILE_WS_CONNECTION_SUCCESS'; 
export const PROFILE_WS_CONNECTION_ERROR: 'PROFILE_WS_CONNECTION_ERROR' = 'PROFILE_WS_CONNECTION_ERROR';
export const PROFILE_WS_CONNECTION_CLOSED: 'PROFILE_WS_CONNECTION_CLOSED' = 'PROFILE_WS_CONNECTION_CLOSED';
export const PROFILE_WS_GET_MESSAGE: 'PROFILE_WS_GET_MESSAGE' = 'PROFILE_WS_GET_MESSAGE';
export const PROFILE_WS_SEND_MESSAGE: 'PROFILE_WS_SEND_MESSAGE' = 'PROFILE_WS_SEND_MESSAGE';
export const PROFILE_WS_CONNECTION_CLOSE: 'PROFILE_WS_CONNECTION_CLOSE' = 'PROFILE_WS_CONNECTION_CLOSE';